### ISSUE TITLE
Resize bottom bar from mobile interface

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#123]
I understand the aim of the bottom bar, but it's taking a lot of space. Can we remove it? 

![image](https://github.com/lil-lab/recnet/assets/3289873/98b9c49d-ca2a-4cf7-8ce9-558b7e26786c)

The home button is equal to clicking the "RecNet" logo at the top-left. Can we add the profile image and rec button in the remaining space at the top bar? 

Alternatively, we can a floating rec button at the bottom-right, like Twitter does:

![image](https://github.com/lil-lab/recnet/assets/3289873/105f1593-4009-43aa-9acb-ee6de336d169)

**Comment by swh00tw** [comment]
I added the bottom navigator because I think
1. Moving the avatar to top-bar makes the top-bar look a little bit full (still doable tho)
2. From user-experience perspective, having a bottom bar will make your thumb easier to reach and navigate to different pages.

The floating button also inherits the second advantage (easier to click), I can change to that if you want.

**Comment by yoavartzi** [comment]
Really good point about user experience. 

Can we make it smaller then? Twitter has better content/bar ratio

**Comment by swh00tw** [comment]
> Really good point about user experience.
> 
> Can we make it smaller then? Twitter has better content/bar ratio

Yea I think that's why Twitter and other social media all have the bottom navigation bar.

I will adjust it to make it smaller!
