### ISSUE TITLE
Re-add all users page to the new design

### ISSUE THREAD

**Issue by yoavartzi** [lil-lab/recnet#126]
It's currently hidden

**Comment by swh00tw** [comment]
Oh, I did not make this page for a reason. Because I think if you want to get all users, you just don't type anything in the search bar and search. Then you will get all users. (I understand you might feel it's a bit implicit?)

Any reason we need "All users" page? 
I guess it's because of the fact that the platform is still new and need a page for new user to discover other users?

Anyways, sorry I should've let you know before I made the decision.

**Comment by yoavartzi** [comment]
Exactly for both. The no input is a bit too implicit. The all users page is
just for the start. We will remove it later.

Thanks!

- Yoav
