### ISSUE TITLE
Improve on showing past cutoffs

### ISSUE THREAD

**Issue by anya-ji** [lil-lab/recnet#23]
Currently we show all past cutoffs from a hardcoded start date. Ideally, we could:
- paginate
- use a week picker

**Comment by yoavartzi** [comment]
@vtjong how far along we are on this? Because if not has been done, we can move it to the UI overhaul

**Comment by yoavartzi** [comment]
This is the current situation and it's not great


![Image](https://github.com/lil-lab/recnet/assets/3289873/e6babb64-340d-40da-9a98-0fdd4ca33c73)




Proposed solution: show most recent 5 elements, and then a date picket to browse the entire history

**Comment by yoavartzi** [comment]
We want to show the most recent k=5 dates, and then a date picker for the rest

**Comment by swh00tw** [comment]
![Screenshot 2024-04-21 at 8 46 13 PM](https://github.com/lil-lab/recnet/assets/71842426/9fecfaa8-5031-4ea4-b970-1b73a8485a73)

Here are the wireframe of two designs, which one is better? @yoavartzi @joannechen1223 

I personally think B is better since it saves more space. A is traditional date picker but in our app, the design like this seems weird since only Tuesdays are clickable. Over 80% of user interface is disabled. It looks weird and not efficient to me.

**Comment by yoavartzi** [comment]
This is a good point. But, A gives a better temporal orientation, which I think is a big plus. I would go for A. Thanks!
